name: BookingYa CI - All Phases

on:
  push:
    branches: [ "main", "estudiantes" ]
  pull_request:
    branches: [ "main", "estudiantes" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run TDD and BDD tests
        run: mvn clean verify

      - name: Build and Start Spring Boot App
        run: |
          mvn package -DskipTests
          java -Dspring.profiles.active=h2 -jar target/*.jar > app_log.txt 2>&1 &

      - name: Wait for API to be ready
        run: npx wait-on tcp:8080 --timeout 180000

      - name: Debug App Startup (on failure)
        if: failure()
        run: |
          echo "------- LOG DE LA APLICACIÓN (SPRING BOOT) -------"
          cat app_log.txt || echo "No se encontró el archivo de log"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ATDD Dependencies
        run: |
          cd "playwright- test atdd"
          npm install
          chmod +x node_modules/.bin/playwright
          npx playwright install --with-deps chromium

      - name: Run ATDD tests
        run: |
          cd "playwright- test atdd"
          npx playwright test